### PR TITLE
Migrate to Astro

### LINKED ISSUE #2: Migrate to Astro
Can I do this?

It'll involve using Node and a number of other tools from my [Astro boilerplate project](https://github.com/cyrus01337/astro-app-boilerplate) that will allow the site to utilise Markdown as page content, which I've achieved before in my personal site ([source](https://github.com/cyrus01337/cyrus01337.co.uk/tree/main/src/content), [preview](https://cyrus01337.co.uk/blogs/why-i-quit-social-media)).

This would involve a total restructure and having to manually style this, though I'm willing to do the heavy lifting in that regard.

### PR DESCRIPTION
**Pull request by cyrus01337**
This resolves #2 by replacing Mkdocs with Astro, with it's content collection and support for MDX replacing Mkdocs's doc-gen functionality.

### CODE REVIEW

**Comment by cyrus01337** [comment]
Safer to say I added a search bar and integrated all content to be indexed in a simple way, while providing the ability to opt out for things like pages that are also considered content.

The latter can be improved if I organise page content into it's own folder, but it's already places unconventionally, so to keep things simple I'll leave it be as the problem is trivial for non-Astro users.

Also added a shadow to the navbar lol, forgot to remove that.

**Comment by cyrus01337** [comment]
I'd like to add a listing but unsure where to go from here, the pipeline also needs to be tested to ensure it publishes correctly.

**Review by haotian2006 — APPROVED** [review]
Got Astro set up on my system and got the site running

**Comment by haotian2006** [comment]
Also you want me to rename the project to something else that not "MyDocs"

**Comment by cyrus01337** [comment]
I don't know what else it could be at the moment, I've yet to come up with anything meaningful regarding personalisation (which also includes changing the title and maybe even the MyDocs base in the URL).

If you have any ideas, by all means.

**Comment by haotian2006** [comment]
Alr Also I can't seem to get the site to be built automatically, github saying it can't get one of the dependencies

**Pull request merged**
