### PR TITLE
Fix pipeline

### PR DESCRIPTION
**Pull request by cyrus01337**
The projects appears to have conflicted packages that I added for Astro in the pipeline. I've gone ahead and resolved the available merge conflicts, then removed the Bun lockfile that shouldn't be present as far as I'm aware.

Also auto-formatted some straggler files.

### CODE REVIEW

**Comment by cyrus01337** [comment]
This can be tested now.

As a side note, be sure to setup Github Pages so that it operates off of Github Actions rather than a set branch as shown below:

**Review by haotian2006 — APPROVED** [review]

**Comment by haotian2006** [comment]
image

I'm still getting a error still

**Comment by haotian2006** [comment]
Ok I fixed it by adding 
  - run: npm install --legacy-peer-deps
  - run: npm run build
  
  but am having a bit of problems with the deploy ment

**Comment by haotian2006** [comment]
Alright removed What I did earlier and fixed a typo in Astro.Config and downgraded eslint to a lower version and site deployed properly

**Comment by cyrus01337** [comment]
Ah, it needs a lock file then.

**Pull request merged**
