### PR TITLE
Import Secrets before running

### PR DESCRIPTION
**Pull request by haotian2006**

### CODE REVIEW

**Comment by haotian2006** [comment]
Secrets were being imported after building which was an Issue so It has been moved to the front

**Review by cyrus01337 — APPROVED** [review]
Don't know how I never noticed this.

**Comment by haotian2006** [comment]
weird discord data is still not loading 
image

**Comment by haotian2006** [comment]
image
image
image

**Comment by cyrus01337** [comment]
If it works fine in development then it's a difference in environment for sure, otherwise we're probably managing the environment incorrectly.

**Comment by haotian2006** [comment]
I've been trying to figure out what's wrong 
image
This for some reason is printing unfined even though the secrets are being imported and printing when I try running a js file using process.env

**Comment by cyrus01337** [comment]
I'll get my tokens setup locally and give it a spin.

**Comment by haotian2006** [comment]
Alright, I got it working. Just had to move the env to before steps

**Pull request merged**
